# rivarly preferences

# ask ChatGPT to generate 10 rivalries for each team while emphasizing:
# 1) historical rivalry/significance of game
# 2) frequency of play
# 3) geographic proximity
# correct any obvious omissions

rivalry_preferences <- list(
  "USC" = c(
    "UCLA",
    "Notre Dame",
    "Stanford",
    "California",
    "Washington",
    "Oregon",
    "Oregon State",
    "Arizona State",
    "Arizona",
    "Utah"
  ),
  "Alabama" = c(
    "Auburn",
    "Tennessee",
    "LSU",
    "Ole Miss",
    "Mississippi State",
    "Georgia",
    "Florida",
    "Texas A&M",
    "Arkansas",
    "Clemson"
  ),
  "Notre Dame" = c(
    "USC",
    "Navy",
    "Michigan",
    "Michigan State",
    "Purdue",
    "Stanford",
    "Boston College",
    "Miami",
    "Northwestern",
    "Indiana"
  ),
  "Oklahoma" = c(
    "Texas",
    "Oklahoma State",
    "Nebraska",
    "Kansas State",
    "Kansas",
    "Missouri",
    "Iowa State",
    "TCU",
    "Baylor",
    "Texas Tech"
  ),
  "Penn State" = c(
    "Pittsburgh",
    "Ohio State",
    "Michigan",
    "Michigan State",
    "West Virginia",
    "Maryland",
    "Rutgers",
    "Iowa",
    "Wisconsin",
    "Syracuse"
  ),
  "Texas" = c(
    "Oklahoma",
    "Texas A&M",
    "Arkansas",
    "Baylor",
    "Texas Tech",
    "TCU",
    "Houston",
    "Rice",
    "SMU",
    "Oklahoma State"
  ),
  "Nebraska" = c(
    "Oklahoma",
    "Colorado",
    "Kansas",
    "Missouri",
    "Iowa State",
    "Kansas State",
    "Iowa",
    "Minnesota",
    "Wisconsin",
    "Oklahoma State"
  ),
  "Houston" = c(
    "Rice",
    "SMU",
    "Texas",
    "Baylor",
    "TCU",
    "Texas A&M",
    "Texas Tech",
    "Tulsa",
    "Memphis",
    "UTSA",
    "Texas State",
    "Sam Houston",
    "Tulane"
  ),
  "Michigan" = c(
    "Ohio State",
    "Michigan State",
    "Minnesota",
    "Notre Dame",
    "Penn State",
    "Wisconsin",
    "Illinois",
    "Indiana",
    "Northwestern",
    "Iowa"
  ),
  "Arkansas" = c(
    "Texas",
    "LSU",
    "Ole Miss",
    "Texas A&M",
    "Mississippi State",
    "Missouri",
    "Oklahoma",
    "Tennessee",
    "Auburn",
    "South Carolina"
  ),
  "Florida State" = c(
    "Florida",
    "Miami",
    "Clemson",
    "Georgia",
    "Virginia Tech",
    "NC State",
    "Louisville",
    "Georgia Tech",
    "Auburn",
    "South Carolina"
  ),
  "Stanford" = c(
    "California",
    "USC",
    "UCLA",
    "Notre Dame",
    "Washington",
    "Oregon",
    "Oregon State",
    "Arizona",
    "Arizona State",
    "Colorado"
  ),
  "Washington" = c(
    "Washington State",
    "Oregon",
    "Oregon State",
    "California",
    "Stanford",
    "USC",
    "UCLA",
    "Arizona",
    "Arizona State",
    "Colorado"
  ),
  "Clemson" = c(
    "South Carolina",
    "Georgia",
    "Florida State",
    "NC State",
    "Wake Forest",
    "Georgia Tech",
    "Virginia Tech",
    "North Carolina",
    "Louisville",
    "Auburn",
    "North Carolina",
    "Duke"
  ),
  "Michigan State" = c(
    "Michigan",
    "Notre Dame",
    "Indiana",
    "Penn State",
    "Ohio State",
    "Northwestern",
    "Purdue",
    "Wisconsin",
    "Minnesota",
    "Iowa"
  ),
  "Missouri" = c(
    "Kansas",
    "Illinois",
    "Nebraska",
    "Oklahoma",
    "Arkansas",
    "Iowa State",
    "Kansas State",
    "Kentucky",
    "Tennessee",
    "South Carolina"
  ),
  "Central Michigan" = c(
    "Western Michigan",
    "Eastern Michigan",
    "Northern Illinois",
    "Ball State",
    "Toledo",
    "Bowling Green",
    "Kent State",
    "Ohio",
    "Akron",
    "Buffalo"
  ),
  "SMU" = c(
    "TCU",
    "Houston",
    "Baylor",
    "Texas",
    "Rice",
    "Texas A&M",
    "Texas Tech",
    "Tulsa",
    "North Texas",
    "Memphis"
  ),
  "Maryland" = c(
    "Virginia",
    "Penn State",
    "West Virginia",
    "Rutgers",
    "North Carolina",
    "Duke",
    "NC State",
    "Wake Forest",
    "Michigan",
    "Ohio State"
  ),
  "East Carolina" = c(
    "NC State",
    "Southern Miss",
    "Memphis",
    "Tulane",
    "UCF",
    "South Florida",
    "Marshall",
    "App State",
    "Charlotte",
    "Virginia Tech",
    "North Carolina",
    "Duke",
    "Clemson",
    "Wake Forest"
  ),
  "Florida" = c(
    "Georgia",
    "Florida State",
    "Tennessee",
    "Miami",
    "LSU",
    "Auburn",
    "Kentucky",
    "Alabama",
    "South Carolina",
    "Ole Miss"
  ),
  "Mississippi State" = c(
    "Ole Miss",
    "Alabama",
    "LSU",
    "Auburn",
    "Arkansas",
    "Tennessee",
    "Vanderbilt",
    "Texas A&M",
    "Kentucky",
    "South Carolina",
    "Georgia",
    "Florida",
    "Southern Miss",
    "Tulane",
    "UL Monroe",
    "Louisiana Tech",
    "Louisiana",
    "Troy"
  ),
  "Ball State" = c(
    "Miami (OH)",
    "Northern Illinois",
    "Central Michigan",
    "Western Michigan",
    "Eastern Michigan",
    "Bowling Green",
    "Toledo",
    "Kent State",
    "Ohio",
    "Akron"
  ),
  "North Texas" = c(
    "SMU",
    "UTSA",
    "Rice",
    "Texas State",
    "UTEP",
    "Tulsa",
    "Houston",
    "Louisiana Tech",
    "Memphis",
    "Middle Tennessee"
  ),
  "Texas Tech" = c(
    "Texas",
    "Texas A&M",
    "Baylor",
    "TCU",
    "Oklahoma",
    "Oklahoma State",
    "Houston",
    "Kansas State",
    "SMU",
    "North Texas",
    "UTEP",
    "UTSA"
  ),
  "UCLA" = c(
    "USC",
    "California",
    "Stanford",
    "Arizona State",
    "Arizona",
    "Oregon",
    "Washington",
    "Oregon State",
    "Washington State",
    "Utah"
  ),
  "Chattanooga" = c(
    "East Tennessee State",
    "Furman",
    "Western Carolina",
    "The Citadel",
    "Samford",
    "Wofford",
    "Mercer",
    "VMI",
    "Jacksonville State",
    "App State"
  ),
  "Georgia" = c(
    "Florida",
    "Auburn",
    "Georgia Tech",
    "Tennessee",
    "South Carolina",
    "Alabama",
    "Clemson",
    "Kentucky",
    "LSU",
    "Vanderbilt"
  ),
  "NC State" = c(
    "North Carolina",
    "Duke",
    "Wake Forest",
    "Clemson",
    "East Carolina",
    "Virginia",
    "Virginia Tech",
    "South Carolina",
    "Maryland",
    "Florida State"
  ),
  "BYU" = c(
    "Utah",
    "Utah State",
    "Boise State",
    "Colorado State",
    "Wyoming",
    "Air Force",
    "UNLV",
    "San Diego State",
    "Arizona",
    "Arizona State"
  ),
  "Southern Miss" = c(
    "Louisiana Tech",
    "Memphis",
    "Tulane",
    "UAB",
    "East Carolina",
    "Marshall",
    "South Alabama",
    "Mississippi State",
    "Ole Miss",
    "Troy"
  ),
  "LSU" = c(
    "Alabama",
    "Ole Miss",
    "Florida",
    "Auburn",
    "Arkansas",
    "Texas A&M",
    "Mississippi State",
    "Georgia",
    "Tennessee",
    "Tulane"
  ),
  "Rutgers" = c(
    "Penn State",
    "Princeton",
    "Syracuse",
    "Maryland",
    "Pittsburgh",
    "Temple",
    "UConn",
    "Boston College",
    "West Virginia",
    "Michigan"
  ),
  "Arizona State" = c(
    "Arizona",
    "USC",
    "UCLA",
    "Utah",
    "Colorado",
    "California",
    "Stanford",
    "Oregon",
    "Washington",
    "Oregon State",
    "BYU",
    "New Mexico",
    "New Mexico State"
  ),
  "Ohio State" = c(
    "Michigan",
    "Penn State",
    "Illinois",
    "Wisconsin",
    "Michigan State",
    "Purdue",
    "Indiana",
    "Iowa",
    "Minnesota",
    "Northwestern"
  ),
  "Pittsburgh" = c(
    "West Virginia",
    "Penn State",
    "Syracuse",
    "Notre Dame",
    "Virginia Tech",
    "Louisville",
    "Boston College",
    "Cincinnati",
    "Temple",
    "Maryland"
  ),
  "Baylor" = c(
    "TCU",
    "Texas",
    "Texas A&M",
    "Texas Tech",
    "Houston",
    "SMU",
    "Oklahoma",
    "Oklahoma State",
    "Rice",
    "Texas State",
    "UTSA",
    "North Texas",
    "Sam Houston",
    "Kansas",
    "Kansas State"
  ),
  "Purdue" = c(
    "Indiana",
    "Illinois",
    "Notre Dame",
    "Ohio State",
    "Michigan State",
    "Northwestern",
    "Iowa",
    "Wisconsin",
    "Minnesota",
    "Michigan"
  ),
  "Louisiana Tech" = c(
    "Southern Miss",
    "UL Monroe",
    "Louisiana",
    "Memphis",
    "Tulane",
    "North Texas",
    "UTEP",
    "Arkansas State",
    "Middle Tennessee",
    "Sam Houston"
  ),
  "Miami (OH)" = c(
    "Ohio",
    "Cincinnati",
    "Ball State",
    "Bowling Green",
    "Toledo",
    "Kentucky",
    "Eastern Michigan",
    "Western Michigan",
    "Central Michigan",
    "Marshall"
  ),
  "Cincinnati" = c(
    "Louisville",
    "Miami (OH)",
    "Pittsburgh",
    "West Virginia",
    "Ohio",
    "Kentucky",
    "Memphis",
    "Houston",
    "UCF",
    "Temple"
  ),
  "Yale" = c(
    "Harvard",
    "Princeton",
    "Brown",
    "Dartmouth",
    "Cornell",
    "Columbia",
    "Pennsylvania",
    "Army",
    "Holy Cross",
    "Amherst"
  ),
  "Utah State" = c(
    "Utah",
    "BYU",
    "Wyoming",
    "Colorado State",
    "Boise State",
    "Nevada",
    "Fresno State",
    "San Diego State",
    "Air Force",
    "Idaho"
  ),
  "Holy Cross" = c(
    "Boston College",
    "Fordham",
    "Colgate",
    "Bucknell",
    "Lehigh",
    "Lafayette",
    "Army",
    "Navy",
    "Georgetown",
    "Brown"
  ),
  "Texas A&M" = c(
    "Texas",
    "LSU",
    "Arkansas",
    "Baylor",
    "Texas Tech",
    "SMU",
    "Rice",
    "Oklahoma",
    "Mississippi State",
    "Alabama"
  ),
  "California" = c(
    "Stanford",
    "USC",
    "UCLA",
    "Washington",
    "Oregon",
    "Oregon State",
    "Arizona",
    "Arizona State",
    "Washington State",
    "Colorado"
  ),
  "Arizona" = c(
    "Arizona State",
    "UCLA",
    "USC",
    "Utah",
    "Colorado",
    "California",
    "Stanford",
    "Oregon",
    "Washington",
    "New Mexico"
  ),
  "Tulsa" = c(
    "SMU",
    "Houston",
    "Oklahoma State",
    "Memphis",
    "Tulane",
    "Rice",
    "North Texas",
    "UTEP",
    "Arkansas State",
    "East Carolina"
  ),
  "North Carolina" = c(
    "NC State",
    "Duke",
    "Virginia",
    "Wake Forest",
    "South Carolina",
    "Clemson",
    "Maryland",
    "Georgia Tech",
    "Tennessee",
    "Virginia Tech"
  ),
  "South Carolina" = c(
    "Clemson",
    "Georgia",
    "North Carolina",
    "Tennessee",
    "Florida",
    "Kentucky",
    "Auburn",
    "Mississippi State",
    "Arkansas",
    "NC State",
    "Ole Miss"
  ),
  "Dartmouth" = c(
    "Princeton",
    "Harvard",
    "Yale",
    "Brown",
    "Cornell",
    "Columbia",
    "Pennsylvania",
    "Army",
    "Holy Cross",
    "Amherst"
  ),
  "Navy" = c(
    "Army",
    "Notre Dame",
    "Air Force",
    "Tulane",
    "SMU",
    "Houston",
    "East Carolina",
    "Temple",
    "William & Mary",
    "Maryland"
  ),
  "Wyoming" = c(
    "Colorado State",
    "Utah State",
    "Air Force",
    "BYU",
    "New Mexico",
    "Boise State",
    "Nevada",
    "Fresno State",
    "San Diego State",
    "Washington State",
    "Oregon State",
    "Montana",
    "Utah",
    "Washington",
    "Oregon"
  ),
  "Utah" = c(
    "BYU",
    "Utah State",
    "Colorado",
    "Arizona State",
    "Arizona",
    "UCLA",
    "USC",
    "Washington",
    "Oregon",
    "Stanford",
    "Washington State",
    "Wyoming"
  ),
  "Brown" = c(
    "Yale",
    "Harvard",
    "Dartmouth",
    "Princeton",
    "Cornell",
    "Columbia",
    "Pennsylvania",
    "Holy Cross",
    "Rhode Island",
    "Army"
  ),
  "Kentucky" = c(
    "Louisville",
    "Tennessee",
    "Florida",
    "Vanderbilt",
    "Georgia",
    "South Carolina",
    "Indiana",
    "Missouri",
    "Ole Miss",
    "West Virginia"
  ),
  "Auburn" = c(
    "Alabama",
    "Georgia",
    "LSU",
    "Florida",
    "Tennessee",
    "Ole Miss",
    "Mississippi State",
    "Arkansas",
    "Clemson",
    "Florida State"
  ),
  "New Mexico" = c(
    "New Mexico State",
    "Wyoming",
    "Colorado State",
    "Air Force",
    "Utah State",
    "BYU",
    "Arizona",
    "UTEP",
    "San Diego State",
    "San José State",
    "Hawai'i",
    "Fresno State",
    "Arizona State"
  ),
  "Miami" = c(
    "Florida State",
    "Florida",
    "Notre Dame",
    "Virginia Tech",
    "Boston College",
    "Georgia Tech",
    "Clemson",
    "North Carolina",
    "NC State",
    "Pittsburgh",
    "Wake Forest",
    "Florida International",
    "Florida Atlantic",
    "South Florida",
    "UCF",
    "Kennesaw State"
  ),
  "Georgia Tech" = c(
    "Georgia",
    "Clemson",
    "Auburn",
    "Florida State",
    "Miami",
    "North Carolina",
    "Duke",
    "Virginia",
    "Alabama",
    "Tennessee"
  ),
  "Tennessee" = c(
    "Alabama",
    "Kentucky",
    "Florida",
    "Vanderbilt",
    "Georgia",
    "Auburn",
    "Ole Miss",
    "South Carolina",
    "LSU",
    "Virginia Tech"
  ),
  "Oklahoma State" = c(
    "Oklahoma",
    "Texas Tech",
    "Kansas State",
    "Tulsa",
    "Iowa State",
    "Baylor",
    "TCU",
    "Texas",
    "Kansas",
    "Missouri",
    "Nebraska",
    "Houston",
    "Texas A&M",
    "North Texas",
    "Arkansas",
    "UTSA",
    "Rice"
  ),
  "Iowa State" = c(
    "Kansas State",
    "Iowa",
    "Missouri",
    "Kansas",
    "Oklahoma State",
    "Nebraska",
    "Colorado",
    "Baylor",
    "TCU",
    "West Virginia",
    "Drake"
  ),
  "Hawai'i" = c(
    "Fresno State",
    "San Diego State",
    "San José State",
    "Nevada",
    "Boise State",
    "UNLV",
    "Utah State",
    "BYU",
    "Air Force",
    "New Mexico"
  ),

  "UL Monroe" = c(
    "Louisiana",
    "Louisiana Tech",
    "Arkansas State",
    "UL Lafayette",
    "South Alabama",
    "Texas State",
    "Troy",
    "Memphis",
    "North Texas",
    "Southern Miss"
  ),
  "App State" = c(
    "Georgia Southern",
    "Western Carolina",
    "Marshall",
    "Coastal Carolina",
    "James Madison",
    "Old Dominion",
    "Georgia State",
    "East Carolina",
    "Charlotte",
    "Troy",
    "North Carolina",
    "Duke",
    "NC State",
    "Louisville",
    "Kentucky",
    "West Virginia"
  ),
  "Temple" = c(
    "Penn State",
    "Pittsburgh",
    "Villanova",
    "Rutgers",
    "Syracuse",
    "Maryland",
    "West Virginia",
    "Navy",
    "Cincinnati",
    "UConn"
  ),
  "Oregon" = c(
    "Oregon State",
    "Washington",
    "Stanford",
    "California",
    "USC",
    "UCLA",
    "Washington State",
    "Arizona",
    "Arizona State",
    "Colorado"
  ),
  "UNLV" = c(
    "Nevada",
    "San Diego State",
    "Fresno State",
    "Boise State",
    "Utah State",
    "Colorado State",
    "Wyoming",
    "Air Force",
    "Hawai'i",
    "New Mexico",
    "Idaho",
    "New Mexico State",
    "San José State",
    "Arizona",
    "Arizona State",
    "Colorado"
  ),
  "Western Michigan" = c(
    "Central Michigan",
    "Eastern Michigan",
    "Ball State",
    "Northern Illinois",
    "Toledo",
    "Bowling Green",
    "Kent State",
    "Ohio",
    "Akron",
    "Buffalo"
  ),
  "McNeese" = c(
    "Northwestern State",
    "Lamar",
    "Sam Houston",
    "Arkansas State",
    "Houston",
    "Louisiana",
    "Louisiana Tech",
    "UL Monroe",
    "Tulane",
    "LSU"
  ),
  "Washington State" = c(
    "Washington",
    "Oregon State",
    "Oregon",
    "Idaho",
    "Boise State",
    "Stanford",
    "California",
    "USC",
    "UCLA",
    "Arizona",
    "Arizona State",
    "Utah",
    "Colorado",
    "Utah State",
    "Fresno State"
  ),
  "Western Carolina" = c(
    "App State",
    "Chattanooga",
    "Furman",
    "The Citadel",
    "Wofford",
    "Samford",
    "Mercer",
    "ETSU",
    "VMI",
    "Elon",
    "East Carolina"
  ),
  "Louisville" = c(
    "Kentucky",
    "Cincinnati",
    "West Virginia",
    "Memphis",
    "Pittsburgh",
    "Virginia Tech",
    "Florida State",
    "Miami",
    "NC State",
    "Syracuse",
    "North Carolina",
    "Western Kentucky",
    "Ohio",
    "Ohio State",
    "App State"
  ),
  "Arkansas State" = c(
    "UL Monroe",
    "Louisiana",
    "Memphis",
    "Southern Miss",
    "Troy",
    "South Alabama",
    "North Texas",
    "Middle Tennessee",
    "Texas State",
    "Louisiana Tech"
  ),

  "Colorado" = c(
    "Colorado State",
    "Nebraska",
    "Utah",
    "Oklahoma",
    "Kansas",
    "Kansas State",
    "Iowa State",
    "Missouri",
    "Arizona",
    "Arizona State"
  ),
  "Furman" = c(
    "The Citadel",
    "Chattanooga",
    "Western Carolina",
    "Wofford",
    "Samford",
    "Mercer",
    "VMI",
    "East Tennessee State",
    "Elon",
    "App State"
  ),
  "Oregon State" = c(
    "Oregon",
    "Washington State",
    "Washington",
    "Stanford",
    "California",
    "USC",
    "UCLA",
    "Arizona",
    "Arizona State",
    "Colorado"
  ),
  "Ole Miss" = c(
    "Mississippi State",
    "LSU",
    "Alabama",
    "Arkansas",
    "Auburn",
    "Tennessee",
    "Texas A&M",
    "Florida",
    "Georgia",
    "Vanderbilt"
  ),
  "Richmond" = c(
    "William & Mary",
    "James Madison",
    "Delaware",
    "Villanova",
    "Towson",
    "Elon",
    "Hampton",
    "Norfolk State",
    "Virginia",
    "VMI",
    "App State",
    "Liberty",
    "Charlotte",
    "Wake Forest",
    "North Carolina",
    "Duke"
  ),
  "Duke" = c(
    "North Carolina",
    "NC State",
    "Wake Forest",
    "Virginia",
    "Clemson",
    "Georgia Tech",
    "Maryland",
    "South Carolina",
    "Tennessee",
    "Florida State"
  ),
  "Cornell" = c(
    "Pennsylvania",
    "Columbia",
    "Yale",
    "Harvard",
    "Princeton",
    "Dartmouth",
    "Brown",
    "Army",
    "Syracuse",
    "Colgate"
  ),
  "Syracuse" = c(
    "Georgetown",
    "Pittsburgh",
    "West Virginia",
    "Boston College",
    "Penn State",
    "Rutgers",
    "Virginia Tech",
    "Miami",
    "UConn",
    "Army"
  ),
  "Indiana" = c(
    "Purdue",
    "Illinois",
    "Michigan State",
    "Michigan",
    "Ohio State",
    "Kentucky",
    "Northwestern",
    "Wisconsin",
    "Iowa",
    "Minnesota"
  ),
  "Bowling Green" = c(
    "Toledo",
    "Miami (OH)",
    "Western Michigan",
    "Eastern Michigan",
    "Central Michigan",
    "Northern Illinois",
    "Kent State",
    "Akron",
    "Ohio",
    "Ball State"
  ),
  "Rice" = c(
    "Houston",
    "SMU",
    "Texas",
    "Texas A&M",
    "Baylor",
    "Tulsa",
    "TCU",
    "North Texas",
    "UTEP",
    "Louisiana Tech"
  ),
  "San José State" = c(
    "Fresno State",
    "Stanford",
    "California",
    "San Diego State",
    "Nevada",
    "Hawai'i",
    "UNLV",
    "Boise State",
    "Utah State",
    "Sacramento State",
    "Idaho",
    "Oregon",
    "Oregon State",
    "Washington",
    "Washington State"
  ),
  "San Diego State" = c(
    "Fresno State",
    "San José State",
    "UNLV",
    "Hawai'i",
    "Boise State",
    "Utah State",
    "Nevada",
    "Arizona",
    "UCLA",
    "New Mexico"
  ),
  "Colorado State" = c(
    "Wyoming",
    "Air Force",
    "Colorado",
    "New Mexico",
    "Utah State",
    "Boise State",
    "Nevada",
    "Fresno State",
    "San Diego State",
    "BYU"
  ),
  "Virginia Tech" = c(
    "Virginia",
    "West Virginia",
    "Miami",
    "North Carolina",
    "NC State",
    "Pittsburgh",
    "Tennessee",
    "Georgia Tech",
    "Duke",
    "Clemson"
  ),
  "Memphis" = c(
    "Cincinnati",
    "Louisville",
    "Southern Miss",
    "Tulane",
    "UCF",
    "Houston",
    "Arkansas State",
    "Middle Tennessee",
    "East Carolina",
    "Ole Miss"
  ),
  "Harvard" = c(
    "Yale",
    "Princeton",
    "Dartmouth",
    "Brown",
    "Cornell",
    "Columbia",
    "Pennsylvania",
    "Army",
    "Holy Cross",
    "Amherst"
  ),
  "Kansas State" = c(
    "Kansas",
    "Iowa State",
    "Oklahoma State",
    "Nebraska",
    "Missouri",
    "Colorado",
    "Texas Tech",
    "Baylor",
    "TCU",
    "West Virginia",
    "Tulsa",
    "Missouri State",
    "Drake",
    "Northern Illinois"
  ),
  "Wisconsin" = c(
    "Minnesota",
    "Iowa",
    "Illinois",
    "Michigan",
    "Michigan State",
    "Ohio State",
    "Northwestern",
    "Purdue",
    "Nebraska",
    "Indiana"
  ),
  "William & Mary" = c(
    "Richmond",
    "James Madison",
    "Delaware",
    "Villanova",
    "Towson",
    "Hampton",
    "Norfolk State",
    "VMI",
    "Virginia",
    "Elon",
    "Virginia Tech",
    "Old Dominion",
    "App State",
    "Liberty",
    "Charlotte",
    "Wake Forest",
    "North Carolina",
    "Duke"
  ),
  "TCU" = c(
    "SMU",
    "Baylor",
    "Texas",
    "Texas Tech",
    "Rice",
    "Houston",
    "Oklahoma",
    "Oklahoma State",
    "Kansas State",
    "West Virginia"
  ),
  "Wake Forest" = c(
    "NC State",
    "Duke",
    "North Carolina",
    "Clemson",
    "Virginia",
    "Georgia Tech",
    "Florida State",
    "South Carolina",
    "Maryland",
    "Virginia Tech",
    "East Carolina",
    "Coastal Carolina",
    "Louisville",
    "App State"
  ),
  "Colgate" = c(
    "Lehigh",
    "Lafayette",
    "Bucknell",
    "Holy Cross",
    "Fordham",
    "Cornell",
    "Army",
    "Navy",
    "Princeton",
    "Georgetown"
  ),
  "Princeton" = c(
    "Yale",
    "Harvard",
    "Pennsylvania",
    "Dartmouth",
    "Columbia",
    "Cornell",
    "Brown",
    "Rutgers",
    "Army",
    "Holy Cross"
  ),
  "Kansas" = c(
    "Missouri",
    "Kansas State",
    "Iowa State",
    "Nebraska",
    "Oklahoma",
    "Oklahoma State",
    "Colorado",
    "Baylor",
    "TCU",
    "Texas Tech"
  ),
  "Tulane" = c(
    "LSU",
    "Southern Miss",
    "Louisiana Tech",
    "Houston",
    "Memphis",
    "Navy",
    "Ole Miss",
    "Arkansas State",
    "UAB",
    "SMU",
    "McNeese",
    "Northwestern State",
    "Louisiana",
    "UL Monroe"
  ),
  "Northern Illinois" = c(
    "Toledo",
    "Ball State",
    "Western Michigan",
    "Eastern Michigan",
    "Central Michigan",
    "Ohio",
    "Miami (OH)",
    "Kent State",
    "Buffalo",
    "Western Kentucky"
  ),
  "New Mexico State" = c(
    "UTEP",
    "New Mexico",
    "Texas State",
    "Louisiana Tech",
    "Sam Houston",
    "UTSA",
    "Arkansas State",
    "Liberty",
    "Texas Tech",
    "Colorado",
    "Arizona",
    "Arizona State",
    "Utah State",
    "Boise State",
    "Wyoming"
  ),
  "Villanova" = c(
    "Delaware",
    "James Madison",
    "Towson",
    "Richmond",
    "Maine",
    "Elon",
    "Rhode Island",
    "Lehigh",
    "William & Mary",
    "New Hampshire"
  ),
  "West Texas A&M" = c(
    "Texas State",
    "Texas Tech",
    "Houston",
    "Rice",
    "New Mexico State",
    "Texas State",
    "New Mexico",
    "Lamar",
    "Baylor",
    "Texas",
    "Texas A&M"
  ),
  "The Citadel" = c(
    "VMI",
    "Furman",
    "Chattanooga",
    "Samford",
    "Wofford",
    "Elon",
    "App State",
    "Western Carolina",
    "Mercer",
    "East Tennessee State",
    "Clemson",
    "South Carolina",
    "Georgia Tech",
    "Florida State"
  ),
  "Louisiana" = c(
    "Louisiana Tech",
    "McNeese",
    "UL Monroe",
    "Arkansas State",
    "South Alabama",
    "Troy",
    "Tulane",
    "Southern Miss",
    "Texas State",
    "UL Lafayette"
  ),
  "Drake" = c(
    "Missouri State",
    "Indiana State",
    "Illinois State",
    "South Dakota State",
    "Southern Illinois",
    "North Dakota State",
    "Western Kentucky",
    "Iowa",
    "Iowa State",
    "Bowling Green"
  ),
  "Pennsylvania" = c(
    "Cornell",
    "Dartmouth",
    "Princeton",
    "Yale",
    "Harvard",
    "Brown",
    "Lafayette",
    "Lehigh",
    "Bucknell",
    "Colgate"
  ),
  "Ohio" = c(
    "Miami (OH)",
    "Kent State",
    "Bowling Green",
    "Toledo",
    "Marshall",
    "Akron",
    "Western Michigan",
    "Eastern Michigan",
    "Ball State",
    "Northern Illinois"
  ),
  "Iowa" = c(
    "Iowa State",
    "Minnesota",
    "Wisconsin",
    "Nebraska",
    "Illinois",
    "Purdue",
    "Michigan State",
    "Northwestern",
    "Indiana",
    "Michigan"
  ),
  "Columbia" = c(
    "Cornell",
    "Princeton",
    "Pennsylvania",
    "Yale",
    "Harvard",
    "Dartmouth",
    "Brown",
    "Fordham",
    "Lehigh",
    "Bucknell"
  ),
  "Minnesota" = c(
    "Wisconsin",
    "Iowa",
    "Michigan",
    "Northwestern",
    "Nebraska",
    "Illinois",
    "Purdue",
    "Ohio State",
    "Michigan State",
    "Indiana"
  ),
  "West Virginia" = c(
    "Pittsburgh",
    "Maryland",
    "Virginia Tech",
    "Penn State",
    "Rutgers",
    "Cincinnati",
    "Kentucky",
    "Miami",
    "Temple",
    "James Madison",
    "Virginia",
    "Marshall"
  ),
  "Marshall" = c(
    "Ohio",
    "Miami (OH)",
    "Western Kentucky",
    "Eastern Kentucky",
    "Western Michigan",
    "Kent State",
    "Toledo",
    "Louisville",
    "Buffalo",
    "Old Dominion",
    "West Virginia",
    "Virginia Tech",
    "Virginia"
  ),
  "Eastern Michigan" = c(
    "Central Michigan",
    "Western Michigan",
    "Toledo",
    "Ball State",
    "Kent State",
    "Northern Illinois",
    "Ohio",
    "Buffalo",
    "Miami (OH)",
    "Akron",
    "Northwestern",
    "Michigan",
    "Michigan State",
    "Illinois"
  ),
  "Illinois" = c(
    "Northwestern",
    "Iowa",
    "Wisconsin",
    "Indiana",
    "Purdue",
    "Michigan",
    "Michigan State",
    "Minnesota",
    "Nebraska",
    "Ohio State"
  ),
  "Kent State" = c(
    "Akron",
    "Ohio",
    "Toledo",
    "Miami (OH)",
    "Buffalo",
    "Eastern Michigan",
    "Northern Illinois",
    "Ball State",
    "Western Michigan",
    "Central Michigan",
    "Illinois",
    "Iowa",
    "Northwestern"
  ),
  "Toledo" = c(
    "Bowling Green",
    "Northern Illinois",
    "Ohio",
    "Kent State",
    "Western Michigan",
    "Central Michigan",
    "Eastern Michigan",
    "Ball State",
    "Miami (OH)",
    "Akron"
  ),
  "VMI" = c(
    "The Citadel",
    "Furman",
    "Chattanooga",
    "Wofford",
    "Samford",
    "Western Carolina",
    "Mercer",
    "East Tennessee State",
    "Elon",
    "Virginia Tech"
  ),
  "Army" = c(
    "Navy",
    "Air Force",
    "Rutgers",
    "Boston College",
    "Massachusetts",
    "Temple",
    "UConn",
    "Colgate",
    "Fordham",
    "Holy Cross",
    "Syracuse",
    "Notre Dame",
    "Penn State"
  ),
  "Virginia" = c(
    "Virginia Tech",
    "North Carolina",
    "Maryland",
    "Wake Forest",
    "Duke",
    "NC State",
    "Miami",
    "Pittsburgh",
    "West Virginia",
    "Boston College"
  ),
  "Southern Illinois" = c(
    "Illinois State",
    "Missouri State",
    "Indiana State",
    "South Dakota State",
    "South Dakota",
    "Northern Arizona",
    "Western Kentucky",
    "Drake",
    "Northwestern"
  ),
  "Lamar" = c(
    "McNeese",
    "Sam Houston",
    "Abilene Christian",
    "Houston Baptist",
    "Central Arkansas",
    "Southeastern Louisiana",
    "Lousiana",
    "Louisiana Tech",
    "Rice",
    "Houston"
  ),
  "Fresno State" = c(
    "San Diego State",
    "Hawai'i",
    "Nevada",
    "Boise State",
    "San José State",
    "UNLV",
    "New Mexico State",
    "Utah State",
    "Colorado State",
    "Wyoming"
  ),
  "Illinois State" = c(
    "Southern Illinois",
    "Western Kentucky",
    "Missouri State",
    "Indiana State",
    "South Dakota State",
    "South Dakota",
    "North Dakota State",
    "Drake",
    "Illinois",
    "Northwestern"
  ),
  "Boston College" = c(
    "Syracuse",
    "Miami",
    "Virginia Tech",
    "Notre Dame",
    "Florida State",
    "Wake Forest",
    "Clemson",
    "NC State",
    "Pittsburgh",
    "Louisville",
    "West Virginia",
    "Rutgers",
    "UConn",
    "Army",
    "Navy"
  ),
  "Northwestern State" = c(
    "Stephen F. Austin",
    "McNeese",
    "Lamar",
    "UL Monroe",
    "Louisiana",
    "Louisiana Tech",
    "Sam Houston",
    "LSU",
    "Arkansas State",
    "Tulane"
  ),
  "Indiana State" = c(
    "Illinois State",
    "Southern Illinois",
    "Missouri State",
    "South Dakota State",
    "South Dakota",
    "North Dakota State",
    "Drake",
    "Illinois",
    "Purdue",
    "Indiana"
  ),
  "Vanderbilt" = c(
    "Tennessee",
    "Kentucky",
    "Ole Miss",
    "Mississippi State",
    "Florida",
    "Georgia",
    "South Carolina",
    "Alabama",
    "Arkansas",
    "LSU",
    "Middle Tennessee",
    "Memphis",
    "Western Kentucky",
    "Louisville",
    "Bowling Green"
  ),
  "UTEP" = c(
    "New Mexico State",
    "Texas Tech",
    "Texas State",
    "UTSA",
    "Louisiana Tech",
    "Southern Miss",
    "Tulane",
    "Houston",
    "Rice",
    "North Texas",
    "Sam Houston",
    "Lamar",
    "New Mexico",
    "Arizona",
    "Arizona State"
  ),
  "Air Force" = c(
    "Army",
    "Navy",
    "Colorado State",
    "Utah State",
    "Wyoming",
    "New Mexico",
    "Boise State",
    "San Diego State",
    "Nevada",
    "Fresno State"
  ),
  "Northwestern" = c(
    "Illinois",
    "Wisconsin",
    "Minnesota",
    "Iowa",
    "Michigan State",
    "Purdue",
    "Indiana",
    "Michigan",
    "Nebraska",
    "Ohio State"
  ),
  "East Tennessee State" = c(
    "The Citadel",
    "Furman",
    "Chattanooga",
    "Wofford",
    "Mercer",
    "VMI",
    "Samford",
    "Western Carolina",
    "App State",
    "Elon"
  ),
  "UConn" = c(
    "Temple",
    "Boston College",
    "Rutgers",
    "Syracuse",
    "West Virginia",
    "Cincinnati",
    "Pittsburgh",
    "UCF",
    "Houston",
    "Tulane",
    "UMass",
    "Penn State",
    "Notre Dame"
  ),
  "Akron" = c(
    "Kent State",
    "Ohio",
    "Toledo",
    "Buffalo",
    "Miami (OH)",
    "Eastern Michigan",
    "Northern Illinois",
    "Ball State",
    "Western Michigan",
    "Central Michigan"
  ),
  "Nevada" = c(
    "Fresno State",
    "UNLV",
    "Boise State",
    "San Diego State",
    "Hawai'i",
    "New Mexico State",
    "Utah State",
    "San José State",
    "Colorado State",
    "Wyoming"
  ),
  "Idaho" = c(
    "Boise State",
    "Eastern Washington",
    "Montana",
    "Montana State",
    "Weber State",
    "Northern Arizona",
    "Portland State",
    "Sacramento State",
    "Southern Utah",
    "Northern Colorado",
    "Idaho State",
    "Wyoming",
    "Utah State",
    "Colorado State",
    "New Mexico",
    "New Mexico State",
    "Utah",
    "Washington State",
    "Washington",
    "Arizona",
    "Arizona State"
  ),
  "UCF" = c(
    "South Florida",
    "Memphis",
    "Houston",
    "Tulane",
    "East Carolina",
    "Temple",
    "Navy",
    "SMU",
    "Tulsa",
    "Cincinnati"
  ),
  "UAB" = c(
    "Southern Miss",
    "Memphis",
    "Tulane",
    "Houston",
    "Marshall",
    "Louisiana Tech",
    "North Texas",
    "Middle Tennessee",
    "Rice",
    "Florida Atlantic"
  ),
  "Boise State" = c(
    "Fresno State",
    "Nevada",
    "Idaho",
    "Wyoming",
    "Colorado State",
    "San Diego State",
    "Air Force",
    "Utah State",
    "San José State",
    "New Mexico State"
  ),
  "Buffalo" = c(
    "Miami (OH)",
    "Ohio",
    "Kent State",
    "Toledo",
    "Akron",
    "Ball State",
    "Western Michigan",
    "Eastern Michigan",
    "Northern Illinois",
    "Central Michigan"
  ),
  "Middle Tennessee" = c(
    "Western Kentucky",
    "Florida Atlantic",
    "Florida International",
    "Marshall",
    "Old Dominion",
    "UAB",
    "Louisiana Tech",
    "North Texas",
    "Southern Miss",
    "Rice"
  ),
  "South Florida" = c(
    "UCF",
    "Memphis",
    "Houston",
    "Tulane",
    "East Carolina",
    "Temple",
    "Navy",
    "SMU",
    "Tulsa",
    "Cincinnati"
  ),
  "Troy" = c(
    "South Alabama",
    "App State",
    "Arkansas State",
    "Louisiana",
    "Georgia Southern",
    "Coastal Carolina",
    "Georgia State",
    "UL Monroe",
    "Texas State",
    "UL Lafayette"
  ),
  "Florida Atlantic" = c(
    "Florida International",
    "Middle Tennessee",
    "Western Kentucky",
    "UAB",
    "Marshall",
    "Old Dominion",
    "Charlotte",
    "Rice",
    "Louisiana Tech",
    "North Texas"
  ),
  "Florida International" = c(
    "Florida Atlantic",
    "Marshall",
    "Middle Tennessee",
    "Western Kentucky",
    "Old Dominion",
    "Charlotte",
    "UAB",
    "North Texas",
    "Louisiana Tech",
    "Rice",
    "South Florida",
    "UCF",
    "Miami",
    "Florida A&M",
    "Jacksonville State"
  ),
  "Florida A&M" = c(
    "Bethune-Cookman",
    "Savannah State",
    "North Carolina A&T",
    "South Carolina State",
    "Howard",
    "Norfolk State",
    "Hampton",
    "Morgan State",
    "Delaware State",
    "Virginia State"
  ),
  "Western Kentucky" = c(
    "Middle Tennessee",
    "Louisville",
    "Marshall",
    "Eastern Kentucky",
    "Murray State",
    "Old Dominion",
    "Florida International",
    "Florida Atlantic",
    "North Texas",
    "UAB"
  ),
  "Texas State" = c(
    "UTSA",
    "New Mexico State",
    "Louisiana",
    "Troy",
    "Arkansas State",
    "South Alabama",
    "Louisiana Tech",
    "Sam Houston",
    "Stephen F. Austin",
    "Texas A&M-Commerce"
  ),
  "UTSA" = c(
    "Texas State",
    "New Mexico State",
    "UTEP",
    "Louisiana Tech",
    "Louisiana",
    "South Alabama",
    "Arkansas State",
    "Texas A&M-Commerce",
    "Stephen F. Austin",
    "Sam Houston"
  ),
  "South Alabama" = c(
    "Troy",
    "Louisiana",
    "Arkansas State",
    "Louisiana Tech",
    "Texas State",
    "South Florida",
    "UL Monroe",
    "Georgia Southern",
    "Coastal Carolina",
    "Georgia State"
  ),
  "Massachusetts" = c(
    "Rhode Island",
    "New Hampshire",
    "Maine",
    "James Madison",
    "Albany",
    "Stony Brook",
    "Delaware",
    "Villanova",
    "Towson",
    "Richmond"
  ),
  "Georgia State" = c(
    "Georgia Southern",
    "App State",
    "Coastal Carolina",
    "Troy",
    "South Alabama",
    "Louisiana",
    "Louisiana Tech",
    "Arkansas State",
    "UL Monroe",
    "Louisiana Lafayette",
    "Georgia",
    "Georgia Tech"
  ),
  "Georgia Southern" = c(
    "Georgia State",
    "App State",
    "Coastal Carolina",
    "Troy",
    "South Alabama",
    "Louisiana",
    "Arkansas State",
    "Louisiana Tech",
    "UL Monroe",
    "Louisiana Lafayette"
  ),
  "Old Dominion" = c(
    "Marshall",
    "James Madison",
    "App State",
    "William & Mary",
    "Liberty",
    "Western Kentucky",
    "Middle Tennessee",
    "Florida Atlantic",
    "Florida International",
    "Charlotte"
  ),
  "Charlotte" = c(
    "Middle Tennessee",
    "Florida Atlantic",
    "Old Dominion",
    "Florida International",
    "Marshall",
    "Western Kentucky",
    "North Texas",
    "Rice",
    "UAB",
    "Louisiana Tech"
  ),
  "Coastal Carolina" = c(
    "App State",
    "Georgia Southern",
    "Georgia State",
    "Troy",
    "South Alabama",
    "Louisiana",
    "Louisiana Tech",
    "Arkansas State",
    "UL Monroe",
    "Louisiana Lafayette",
    "East Carolina",
    "South Carolina",
    "North Carolina"
  ),
  "Liberty" = c(
    "Virginia Tech",
    "Old Dominion",
    "James Madison",
    "Eastern Kentucky",
    "Western Kentucky",
    "Coastal Carolina",
    "App State",
    "Marshall",
    "Charlotte",
    "William & Mary",
    "Virginia"
  ),
  "James Madison" = c(
    "William & Mary",
    "Old Dominion",
    "Richmond",
    "Delaware",
    "Villanova",
    "Massachusetts",
    "Liberty",
    "Albany",
    "Towson",
    "New Hampshire"
  ),
  "Jacksonville State" = c(
    "Samford",
    "Furman",
    "The Citadel",
    "Chattanooga",
    "Western Carolina",
    "Wofford",
    "East Tennessee State",
    "Mercer",
    "VMI",
    "Elon"
  ),
  "Sam Houston" = c(
    "Stephen F. Austin",
    "Lamar",
    "Louisiana Tech",
    "Northwestern State",
    "Louisiana",
    "Texas State",
    "Houston",
    "McNeese",
    "Tulane",
    "Baylor"
  ),
  "Kennesaw State" = c(
    "Mercer",
    "East Tennessee State",
    "The Citadel",
    "Chattanooga",
    "Furman",
    "Wofford",
    "Samford",
    "VMI",
    "Elon",
    "Western Carolina"
  ),
  "Missouri State" = c(
    "Illinois State",
    "Southern Illinois",
    "Indiana State",
    "South Dakota State",
    "South Dakota",
    "North Dakota State",
    "Drake",
    "Missouri",
    "Kansas",
    "Arkansas State"
  ),
  "Delaware" = c(
    "Villanova",
    "James Madison",
    "William & Mary",
    "Richmond",
    "Towson",
    "New Hampshire",
    "Maine",
    "Rhode Island",
    "Albany",
    "Massachusetts"
  )
)

saveRDS(
  rivalry_preferences,
  file = "simulation_world/data/rivalry_preferences.rds"
)
